import { useMemo, useState } from 'react';
import { AlertCircle, Banknote, Check, ClipboardList, ExternalLink, FileText, Plus, Trash2, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useApp } from '../context/AppContext';
import { Button, Card, EmptyState, Field, Input, Select, StatusBadge, Textarea, formatIDR } from './ui-shared';
import { supabase } from '../lib/supabase';
import type { BizTrip } from '../lib/types';

type ReceiptReviewStatus = 'pending' | 'approved' | 'partial' | 'rejected';
type ReviewRow = { id:string; receiptId:string; category:string; description:string; claimed:number; approved:number; status:ReceiptReviewStatus; note:string; fileUrl:string|null };
type MovementRow = { id:string; name:string; component:string; nominal:number; direction:'Refund'|'Reimburse'; ptBurden:string };
type DetailRow = { holder:string; component:string; advance:number; claimed:number; approved:number; difference:number; direction:'Refund'|'Reimburse'|'Settled'; pt:string };

const norm = (v:string) => v.toLowerCase().replace(/[^a-z0-9]/g,'');
const componentMatch = (note:string, category:string) => {
  const n=norm(note), c=norm(category); const aliases:Record<string,string[]>={bbm:['bbm','fuel'],etoll:['etoll','toll'],'pettycash':['pettycash'],'akomodasi':['akomodasi','hotel']};
  return (aliases[c]??[c]).some(k=>n.includes(k));
};

export function SettlementReview({ onPrint }: { onPrint:(id:string)=>void }) {
  const { profile }=useAuth();
  const { trips, settlementReceipts, settlementClaimRows, disburseRows, activePTMaster, updateTrip, showToast, refresh }=useApp();
  const [selected,setSelected]=useState<BizTrip|null>(null); const [reviewRows,setReviewRows]=useState<ReviewRow[]>([]); const [costRows,setCostRows]=useState<MovementRow[]>([]); const [settleNote,setSettleNote]=useState(''); const [saving,setSaving]=useState(false);
  const queue=useMemo(()=>trips.filter(t=>['Pending HR Settlement Review','Pending Refund Verification','Pending HR Finance Process'].includes(t.status)),[trips]);
  const isRefundVerification=selected?.status==='Pending Refund Verification'; const isFinanceProcess=selected?.status==='Pending HR Finance Process';
  const receipts=(id:string)=>settlementReceipts.filter(r=>r.trip_id===id&&r.category!=='Refund Transfer Proof'); const refundProof=(id:string)=>settlementReceipts.find(r=>r.trip_id===id&&r.category==='Refund Transfer Proof');
  const ptOptions=(current?:string)=>{const a=activePTMaster.map(p=>p.name);return current&&!a.includes(current)?[current,...a]:a}; const defaultPT=(t:BizTrip)=>t.company_burden?.[0]||activePTMaster[0]?.name||'';
  const advanceRows=(t:BizTrip)=>disburseRows.filter(r=>r.trip_id===t.id);
  const holderForReceipt=(t:BizTrip,row:ReviewRow)=>{
    const desc=norm(row.description); const candidates=advanceRows(t).filter(a=>componentMatch(a.component_note||'',row.category));
    const byName=candidates.find(a=>desc.includes(norm(a.name))); return byName?.name || (candidates.length===1?candidates[0].name:t.requester_name);
  };
  const details=useMemo<DetailRow[]>(()=>{if(!selected)return[]; const adv=advanceRows(selected).filter(a=>['bbm','etoll','pettycash','akomodasi'].some(c=>componentMatch(a.component_note||'',c)));
    const keys=new Map<string,{holder:string;component:string;advance:number;claimed:number;approved:number;pt:string}>();
    adv.forEach(a=>{const component=['BBM','E-Toll','Pettycash','Akomodasi'].find(c=>componentMatch(a.component_note||'',c))||a.component_note; const key=`${a.name}::${component}`; const old=keys.get(key); keys.set(key,{holder:a.name,component,advance:(old?.advance||0)+Number(a.nominal||0),claimed:old?.claimed||0,approved:old?.approved||0,pt:a.pt_burden||defaultPT(selected)})});
    reviewRows.forEach(r=>{const holder=holderForReceipt(selected,r); const component=r.category; const key=`${holder}::${component}`; const old=keys.get(key); keys.set(key,{holder,component,advance:old?.advance||0,claimed:(old?.claimed||0)+r.claimed,approved:(old?.approved||0)+r.approved,pt:old?.pt||defaultPT(selected)})});
    return [...keys.values()].map(x=>{const difference=x.approved-x.advance;return {...x,difference,direction:difference>0?'Reimburse':difference<0?'Refund':'Settled'} as DetailRow});
  },[selected,reviewRows,disburseRows]);
  const movementTotal=details.reduce((s,d)=>s+Math.abs(d.difference),0); const claimedActual=reviewRows.reduce((s,r)=>s+r.claimed,0); const approvedActual=reviewRows.reduce((s,r)=>s+r.approved,0); const advanceAccountable=Number(selected?.cost_data?.accountable?.total)||0; const advanceTotal=Number(selected?.cost_grand_total)||0; const nonAccountable=Number(selected?.cost_data?.nonAccountable?.total)||0;
  const reimbursementTotal=details.filter(d=>d.direction==='Reimburse').reduce((s,d)=>s+d.difference,0); const refundTotal=details.filter(d=>d.direction==='Refund').reduce((s,d)=>s+Math.abs(d.difference),0); const net=reimbursementTotal-refundTotal;
  const expectedMovementTotal=Math.abs(net); const costTotal=costRows.reduce((s,r)=>s+Number(r.nominal||0),0); const costDifference=costTotal-expectedMovementTotal; const allReviewed=reviewRows.length===0||reviewRows.every(r=>r.status!=='pending');

  const buildMovementRows=(t:BizTrip):MovementRow[]=>{
    const netByHolder=new Map<string,{name:string;amount:number;pt:string;components:string[]}>(); details.forEach(d=>{if(!d.difference)return; const key=d.holder; const old=netByHolder.get(key)||{name:d.holder,amount:0,pt:d.pt||defaultPT(t),components:[]}; old.amount+=d.difference; old.components.push(`${d.component} ${d.difference>0?'+':'-'}${formatIDR(Math.abs(d.difference))}`); netByHolder.set(key,old)});
    return [...netByHolder.values()].filter(x=>x.amount!==0).map(x=>({id:crypto.randomUUID(),name:x.name,component:x.components.join(' · '),nominal:Math.abs(x.amount),direction:x.amount>0?'Reimburse':'Refund',ptBurden:x.pt}));
  };
  const startReview=(t:BizTrip)=>{setSelected(t);setSettleNote(t.settlement_note??''); if(t.status==='Pending Refund Verification'||t.status==='Pending HR Finance Process'){setReviewRows([]);setCostRows(settlementClaimRows.filter(r=>r.trip_id===t.id).map(r=>({id:r.id,name:r.name,component:r.name,nominal:Number(r.nominal)||0,direction:r.claim_status,ptBurden:r.pt_burden})));return;} const rows=receipts(t.id).map(r=>({id:r.id,receiptId:r.id,category:r.category,description:r.description||'',claimed:Number(r.amount)||0,approved:r.hr_approved_amount!=null?Number(r.hr_approved_amount):Number(r.amount)||0,status:(r.hr_status as ReceiptReviewStatus)||'pending',note:r.hr_note||'',fileUrl:r.file_base64||null})); setReviewRows(rows); const existing=settlementClaimRows.filter(r=>r.trip_id===t.id); setCostRows(existing.length?existing.map(r=>({id:r.id,name:r.name,component:r.name,nominal:Number(r.nominal)||0,direction:r.claim_status,ptBurden:r.pt_burden})):[])};
  const updateReview=(id:string,p:Partial<ReviewRow>)=>setReviewRows(rs=>rs.map(r=>r.id===id?{...r,...p}:r)); const updateStatus=(r:ReviewRow,s:ReceiptReviewStatus)=>updateReview(r.id,{status:s,approved:s==='approved'?r.claimed:s==='rejected'?0:r.approved});
  const autoFill=()=>{if(selected)setCostRows(buildMovementRows(selected))}; const updateCost=(id:string,p:Partial<MovementRow>)=>setCostRows(rs=>rs.map(r=>r.id===id?{...r,...p}:r));
  const persist=async()=>{if(!selected)return; for(const r of reviewRows){const q=await supabase.from('settlement_receipts').update({hr_status:r.status,hr_approved_amount:r.approved,hr_note:r.note||null}).eq('id',r.receiptId);if(q.error)throw q.error} const del=await supabase.from('settlement_claim_rows').delete().eq('trip_id',selected.id);if(del.error)throw del.error; for(let i=0;i<costRows.length;i++){const r=costRows[i];if(r.nominal<=0)continue;const q=await supabase.from('settlement_claim_rows').insert({id:crypto.randomUUID(),trip_id:selected.id,name:r.component?`${r.name} — ${r.component}`:r.name,nominal:r.nominal,claim_status:r.direction,pt_burden:r.ptBurden,sort_order:i});if(q.error)throw q.error}};
  const finalize=async()=>{if(!selected)return;if(!allReviewed)return showToast('error','Semua receipt harus direview.'); if(Math.abs(costDifference)>.01)return showToast('error',`Total Table B harus sama dengan net refund/reimbursement ${formatIDR(expectedMovementTotal)}.`); if(costRows.some(r=>r.nominal>0&&!r.ptBurden))return showToast('error','Semua movement wajib memiliki Cost Center.'); setSaving(true);try{await persist(); const next:BizTrip['status']=net>0?'Pending Reimbursement Approval':net<0?'Pending Refund':'Completed';const now=new Date().toISOString();await updateTrip(selected.id,{status:next,realization_total:claimedActual,approved_total:approvedActual,settlement_result:net>0?`Reimbursement - ${net}`:net<0?`Refund - ${Math.abs(net)}`:'Settled',settlement_note:settleNote||null,settlement_reviewed_by:profile?.name??'',settlement_reviewed_at:now,settlement_number:selected.settlement_number||`STL-${new Date().getFullYear()}-${selected.id.slice(0,4).toUpperCase()}`,completed_at:next==='Completed'?now:null,cost_data:{...(selected.cost_data??{}),reimbursementApprovals:{}}});await supabase.from('trip_tracking').insert({trip_id:selected.id,actor_name:profile?.name??'',actor_role:'HR Manager',action:'Settlement reviewed',from_status:selected.status,to_status:next,remarks:`Reimburse ${formatIDR(reimbursementTotal)} · Refund ${formatIDR(refundTotal)} · Net ${formatIDR(Math.abs(net))}`});showToast('success',net>0?'Reimbursement dikirim ke approval Direksi Cost Center.':net<0?'Pegawai perlu melakukan refund.':'Settlement completed.');setSelected(null);refresh()}catch(e:any){showToast('error',e.message)}finally{setSaving(false)}};
  const completeFinance=async()=>{if(!selected)return;setSaving(true);try{const now=new Date().toISOString();await updateTrip(selected.id,{status:'Completed',completed_at:now});await supabase.from('trip_tracking').insert({trip_id:selected.id,actor_name:profile?.name??'',actor_role:'HR Manager',action:'Reimbursement sent to Finance',from_status:'Pending HR Finance Process',to_status:'Completed',remarks:settleNote||'Approved reimbursement forwarded to Finance'});showToast('success','Reimbursement sudah diproses ke Finance. Trip Completed.');setSelected(null);refresh()}catch(e:any){showToast('error',e.message)}finally{setSaving(false)}};
  const proof=selected?refundProof(selected.id):undefined; const refundAmount=selected?Math.max(0,Number(selected.cost_data?.accountable?.total||0)-Number(selected.approved_total||0)):0;
  const verifyRefund=async()=>{if(!selected||!proof)return;setSaving(true);try{const now=new Date().toISOString();await supabase.from('settlement_receipts').update({hr_status:'approved',hr_approved_amount:Number(proof.amount)||refundAmount,hr_note:settleNote||'Refund verified by HR'}).eq('id',proof.id);await updateTrip(selected.id,{status:'Completed',settlement_result:`Refund Completed - ${refundAmount}`,completed_at:now});await supabase.from('trip_tracking').insert({trip_id:selected.id,actor_name:profile?.name??'',actor_role:'HR Manager',action:'Refund verified',from_status:'Pending Refund Verification',to_status:'Completed',remarks:`Refund ${formatIDR(refundAmount)} verified`});setSelected(null);refresh()}finally{setSaving(false)}};

  return <div className="space-y-6 animate-slide-up max-w-6xl mx-auto"><div><h2 className="text-xl font-bold">Settlement Review</h2><p className="text-sm text-slate-500">HR Manager · {queue.length} menunggu proses</p></div>
  {!selected?<Card className="p-6">{queue.length===0?<EmptyState icon={<ClipboardList className="w-6 h-6"/>} title="Tidak ada settlement menunggu"/>:<div className="space-y-2">{queue.map(t=><div key={t.id} className="p-4 ring-1 ring-slate-100 rounded-xl flex justify-between"><div><strong>{t.requester_name}</strong><div className="text-xs text-slate-500">{t.purpose}</div></div><div className="flex gap-2 items-center"><StatusBadge status={t.status}/><Button size="sm" onClick={()=>startReview(t)}>Process</Button></div></div>)}</div>}</Card>:
  isFinanceProcess?<Card className="p-6 space-y-4"><h3 className="font-bold">HR Process to Finance</h3><p className="text-sm">Reimbursement sudah disetujui seluruh Direksi Cost Center.</p>{costRows.map(r=><div key={r.id} className="p-3 bg-slate-50 rounded-xl text-sm flex justify-between"><span>{r.name} · {r.ptBurden}</span><strong>{formatIDR(r.nominal)}</strong></div>)}<Field label="HR Notes"><Textarea value={settleNote} onChange={e=>setSettleNote(e.target.value)}/></Field><div className="flex justify-end"><Button disabled={saving} onClick={completeFinance}>Process to Finance & Complete</Button></div></Card>:
  isRefundVerification?<Card className="p-6 space-y-4"><h3 className="font-bold">Refund Verification</h3><SummaryBox label="Refund" value={refundAmount}/>{proof?.file_base64&&<a href={proof.file_base64} target="_blank" rel="noreferrer" className="text-brand-600 text-sm flex gap-1"><ExternalLink className="w-4 h-4"/>Lihat Bukti</a>}<Button disabled={!proof||saving} onClick={verifyRefund}>Verify & Complete</Button></Card>:
  <><Card className="p-6 space-y-4"><div className="flex justify-between"><div><h3 className="font-bold">Settlement — {selected.requester_name}</h3><p className="text-xs text-slate-500">{selected.purpose}</p></div><button onClick={()=>setSelected(null)}>Tutup</button></div><div className="grid md:grid-cols-4 gap-3"><SummaryBox label="Grand Advance" value={advanceTotal}/><SummaryBox label="Non-Accountable" value={nonAccountable}/><SummaryBox label="Advance Accountable" value={advanceAccountable}/><SummaryBox label="Actual Approved" value={approvedActual}/></div>
  <div className="overflow-x-auto"><h4 className="text-sm font-bold mb-2">Summary per Pemegang & Komponen</h4><table className="w-full text-xs border-collapse"><thead><tr className="bg-slate-50"><TH>Pemegang</TH><TH>Komponen</TH><TH>Advance</TH><TH>Claimed</TH><TH>Approved</TH><TH>Selisih</TH><TH>Arah</TH></tr></thead><tbody>{details.map((d,i)=><tr key={`${d.holder}-${d.component}-${i}`}><TD>{d.holder}</TD><TD>{d.component}</TD><TD>{formatIDR(d.advance)}</TD><TD>{formatIDR(d.claimed)}</TD><TD>{formatIDR(d.approved)}</TD><TD>{formatIDR(Math.abs(d.difference))}</TD><TD><strong>{d.direction}</strong></TD></tr>)}</tbody></table></div><div className="grid md:grid-cols-3 gap-3"><SummaryBox label="Total Reimbursement" value={reimbursementTotal}/><SummaryBox label="Total Refund" value={refundTotal}/><SummaryBox label={net>=0?'Net Reimbursement':'Net Refund'} value={Math.abs(net)}/></div></Card>
  <Card className="p-6 space-y-3"><h3 className="font-bold">A. Review Receipt Aktual</h3>{reviewRows.map(r=><div key={r.id} className="p-3 border rounded-xl grid md:grid-cols-5 gap-2"><div><strong>{r.category}</strong><div className="text-[11px] text-slate-500">{r.description}</div></div><Input value={formatIDR(r.claimed)} disabled/><Input type="number" value={r.approved} onChange={e=>updateReview(r.id,{approved:Number(e.target.value)||0})}/><Select value={r.status} onChange={e=>updateStatus(r,e.target.value as ReceiptReviewStatus)}><option value="pending">Pending</option><option value="approved">Approved</option><option value="partial">Partial</option><option value="rejected">Rejected</option></Select>{r.fileUrl?<a href={r.fileUrl} target="_blank" rel="noreferrer" className="text-brand-600">Lihat Bukti</a>:<span/>}</div>)}</Card>
  <Card className="p-6 space-y-4"><div className="flex justify-between flex-wrap gap-2"><div><h3 className="font-bold">B. Refund / Reimbursement Allocation</h3><p className="text-xs text-slate-500">Hanya selisih uang yang benar-benar bergerak. HR dapat menentukan penerima/pengembali dan Cost Center secara manual.</p></div><div className="flex gap-2"><Button variant="secondary" size="sm" onClick={autoFill}>Auto-Fill Movement</Button><Button variant="secondary" size="sm" icon={<Plus className="w-3 h-3"/>} onClick={()=>setCostRows(rs=>[...rs,{id:crypto.randomUUID(),name:selected.requester_name,component:'',nominal:0,direction:net>=0?'Reimburse':'Refund',ptBurden:defaultPT(selected)}])}>Add Row</Button></div></div>{costRows.map(r=><div key={r.id} className="grid md:grid-cols-6 gap-2"><Input value={r.name} onChange={e=>updateCost(r.id,{name:e.target.value})}/><Input value={r.component} onChange={e=>updateCost(r.id,{component:e.target.value})}/><Select value={r.direction} onChange={e=>updateCost(r.id,{direction:e.target.value as any})}><option>Reimburse</option><option>Refund</option></Select><Input type="number" value={r.nominal} onChange={e=>updateCost(r.id,{nominal:Number(e.target.value)||0})}/><Select value={r.ptBurden} onChange={e=>updateCost(r.id,{ptBurden:e.target.value})}>{ptOptions(r.ptBurden).map(p=><option key={p}>{p}</option>)}</Select><button onClick={()=>setCostRows(rs=>rs.filter(x=>x.id!==r.id))}><Trash2 className="w-4 h-4 text-rose-500"/></button></div>)}<div className="grid md:grid-cols-3 gap-3"><SummaryBox label="Table B" value={costTotal}/><SummaryBox label="Expected Net Movement" value={expectedMovementTotal}/><SummaryBox label="Selisih" value={costDifference}/></div>{Math.abs(costDifference)>.01&&<div className="text-xs text-rose-600 flex gap-2"><AlertCircle className="w-4 h-4"/>Table B harus sama dengan net refund/reimbursement.</div>}<Field label="HR Settlement Notes"><Textarea value={settleNote} onChange={e=>setSettleNote(e.target.value)}/></Field><div className="flex justify-between"><Button variant="secondary" icon={<FileText className="w-3 h-3"/>} onClick={()=>onPrint(selected.id)}>Cetak PDF Settlement</Button><Button disabled={saving||!allReviewed||Math.abs(costDifference)>.01} icon={<Check className="w-3 h-3"/>} onClick={finalize}>Approve Settlement</Button></div></Card></>}
  </div>;
}
function SummaryBox({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-slate-50 border p-4"><div className="text-xs text-slate-400">{label}</div><div className="font-bold mt-1">{formatIDR(value)}</div></div>}
function TH({children}:{children:any}){return <th className="border px-2 py-2 text-left">{children}</th>} function TD({children}:{children:any}){return <td className="border px-2 py-2">{children}</td>}
