import { useState, useMemo } from 'react';
import { MapPin, Plus, Trash2, Upload, Camera, FileText, Send, AlertCircle, RotateCcw, Banknote, CheckCircle2 } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useApp } from '../context/AppContext';
import { Card, Button, Input, Select, Field, Textarea, EmptyState, StatusBadge, formatIDR } from './ui-shared';
import { RECEIPT_CATEGORIES } from '../lib/constants';
import { uid, formatDate, daysBetween } from '../lib/utils';
import { supabase } from '../lib/supabase';
import type { BizTrip } from '../lib/types';

type ReceiptInput = { id: string; category: string; description: string; amount: number; fileUrl: string | null; fileName?: string | null; uploading: boolean; };
const MAX_UPLOAD_BYTES = 1024 * 1024;

async function prepareAttachment(file: File): Promise<File> {
  if (file.size > MAX_UPLOAD_BYTES) throw new Error('Ukuran file maksimal 1 MB');
  if (!file.type.startsWith('image/')) return file;
  const source = await createImageBitmap(file);
  const scale = Math.min(1, 600 / source.width, 600 / source.height);
  const width = Math.max(1, Math.round(source.width * scale));
  const height = Math.max(1, Math.round(source.height * scale));
  const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height;
  const ctx = canvas.getContext('2d'); if (!ctx) throw new Error('Browser tidak dapat memproses gambar');
  ctx.drawImage(source, 0, 0, width, height); source.close();
  const type = file.type === 'image/png' ? 'image/png' : 'image/jpeg';
  const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, type, 0.9));
  if (!blob) throw new Error('Gagal memproses gambar');
  if (blob.size > MAX_UPLOAD_BYTES) throw new Error('Hasil kompresi gambar masih lebih dari 1 MB');
  return new File([blob], `${file.name.replace(/\.[^.]+$/, '')}_600.${type === 'image/png' ? 'png' : 'jpg'}`, { type, lastModified: Date.now() });
}

export function SettlementForm({ setSelectedTrip }: { setSelectedTrip: (id: string) => void; }) {
  const { profile } = useAuth(); const { trips, updateTrip, showToast, refresh } = useApp();
  const [selected, setSelected] = useState<BizTrip | null>(null); const [workResult, setWorkResult] = useState(''); const [realDays, setRealDays] = useState(1); const [pendingTask, setPendingTask] = useState(''); const [nextProject, setNextProject] = useState(''); const [receipts, setReceipts] = useState<ReceiptInput[]>([]);
  const [refundProofs, setRefundProofs] = useState<Record<string, string | null>>({}); const [refundUploadingTrip, setRefundUploadingTrip] = useState<string | null>(null); const [refundSubmittingTrip, setRefundSubmittingTrip] = useState<string | null>(null);
  const queue = useMemo(() => trips.filter((t) => t.user_id === profile?.id && (t.status === 'On Trip' || t.status === 'Pending Settlement')), [trips, profile]);
  const refundQueue = useMemo(() => trips.filter((t) => t.user_id === profile?.id && t.status === 'Pending Refund'), [trips, profile]);
  const bandingQueue = useMemo(() => trips.filter((t) => t.user_id === profile?.id && t.status === 'Rejected' && !!t.settlement_result), [trips, profile]);
  const startReport = (t: BizTrip) => { setSelectedTrip(t.id); setSelected(t); setWorkResult(t.work_result ?? ''); setRealDays(t.total_days || daysBetween(t.departure_date, t.return_date)); setPendingTask(t.pending_task ?? ''); setNextProject(t.next_project ?? ''); setReceipts([]); };
  const addReceipt = () => setReceipts((rows) => [...rows, { id: uid(), category: RECEIPT_CATEGORIES[0], description: '', amount: 0, fileUrl: null, fileName: null, uploading: false }]);
  const updateReceipt = (id: string, patch: Partial<ReceiptInput>) => setReceipts((rows) => rows.map((row) => row.id === id ? { ...row, ...patch } : row)); const removeReceipt = (id: string) => setReceipts((rows) => rows.filter((row) => row.id !== id));
  const uploadReceiptImage = async (id: string, file: File | null) => { if (!file) return; updateReceipt(id, { uploading: true }); try { const prepared = await prepareAttachment(file); const path = `receipts/${selected?.id || 'settlement'}_${Date.now()}_${uid()}.${prepared.name.split('.').pop()}`; const { error } = await supabase.storage.from('receipts').upload(path, prepared, { contentType: prepared.type }); if (error) throw error; const { data } = supabase.storage.from('receipts').getPublicUrl(path); updateReceipt(id, { fileUrl: data.publicUrl, fileName: prepared.name, uploading: false }); showToast('success', 'Bukti berhasil diunggah'); } catch (e: any) { updateReceipt(id, { uploading: false }); showToast('error', 'Gagal upload bukti: ' + e.message); } };
  const validation = useMemo(() => { const errors: string[] = []; if (!workResult.trim()) errors.push('Laporan Hasil Pekerjaan wajib diisi'); if (realDays < 1) errors.push('Total hari riil wajib diisi'); receipts.forEach((r, i) => { if (!r.category) errors.push(`Receipt ${i + 1}: kategori wajib diisi`); if (r.amount > 0 && !r.fileUrl) errors.push(`Receipt ${i + 1}: nominal diisi tetapi bukti belum diunggah`); }); return errors; }, [workResult, realDays, receipts]);
  const totalActual = receipts.reduce((sum, r) => sum + Number(r.amount || 0), 0); const canSubmit = validation.length === 0 && workResult.trim().length > 0;
  const submit = async () => { if (!selected || !canSubmit) return showToast('error', `Form belum lengkap: ${validation.length} validasi`); try { const { error: d } = await supabase.from('settlement_receipts').delete().eq('trip_id', selected.id).neq('category', 'Refund Transfer Proof'); if (d) throw d; for (const r of receipts) { const { error } = await supabase.from('settlement_receipts').insert({ trip_id: selected.id, category: r.category, description: r.description, amount: r.amount, file_name: r.fileName ?? null, file_base64: r.fileUrl, hr_status: 'pending', hr_approved_amount: null, hr_note: null }); if (error) throw error; } await updateTrip(selected.id, { work_result: workResult, total_days: realDays, pending_task: pendingTask || null, next_project: nextProject || null, realization_total: totalActual, settlement_submitted_by: profile?.name ?? '', settlement_submitted_at: new Date().toISOString(), status: 'Pending HR Settlement Review' }); await supabase.from('trip_tracking').insert({ trip_id: selected.id, actor_name: profile?.name ?? '', actor_role: 'Employee', action: 'Settlement submitted', from_status: selected.status, to_status: 'Pending HR Settlement Review', remarks: `Realisasi diajukan ${formatIDR(totalActual)}` }); showToast('success', 'Laporan settlement berhasil dikirim ke HR'); setSelected(null); setReceipts([]); refresh(); } catch (e: any) { showToast('error', 'Gagal submit settlement: ' + e.message); } };
  const getRefundAmount = (t: BizTrip) => Math.max(0, (Number(t.cost_data?.accountable?.total) || 0) - (Number(t.approved_total) || 0));
  const uploadRefundProof = async (t: BizTrip, file: File | null) => { if (!file) return; setRefundUploadingTrip(t.id); try { const prepared = await prepareAttachment(file); const path = `refunds/${t.id}_refund_${Date.now()}.${prepared.name.split('.').pop()}`; const { error } = await supabase.storage.from('receipts').upload(path, prepared, { contentType: prepared.type }); if (error) throw error; const { data } = supabase.storage.from('receipts').getPublicUrl(path); setRefundProofs((p) => ({ ...p, [t.id]: data.publicUrl })); showToast('success', 'Bukti transfer refund berhasil diunggah'); } catch (e: any) { showToast('error', 'Gagal upload bukti refund: ' + e.message); } finally { setRefundUploadingTrip(null); } };
  const submitRefundProof = async (t: BizTrip) => { const url = refundProofs[t.id]; if (!url) return showToast('error', 'Bukti transfer refund wajib diunggah'); const amount = getRefundAmount(t); if (amount <= 0) return showToast('error', 'Nominal refund tidak ditemukan'); setRefundSubmittingTrip(t.id); try { await supabase.from('settlement_receipts').delete().eq('trip_id', t.id).eq('category', 'Refund Transfer Proof'); await supabase.from('settlement_receipts').insert({ trip_id: t.id, category: 'Refund Transfer Proof', description: 'Bukti transfer pengembalian dana perjalanan dinas', amount, file_base64: url, hr_status: 'pending', hr_approved_amount: null, hr_note: null }); await updateTrip(t.id, { status: 'Pending Refund Verification' }); await supabase.from('trip_tracking').insert({ trip_id: t.id, actor_name: profile?.name ?? '', actor_role: 'Employee', action: 'Refund transfer proof submitted', from_status: 'Pending Refund', to_status: 'Pending Refund Verification', remarks: `Refund ${formatIDR(amount)}` }); setRefundProofs((p) => ({ ...p, [t.id]: null })); showToast('success', 'Bukti refund berhasil dikirim dan menunggu verifikasi HR'); refresh(); } catch (e: any) { showToast('error', 'Gagal submit bukti refund: ' + e.message); } finally { setRefundSubmittingTrip(null); } };
  const ajukanBanding = async (t: BizTrip) => { const reason = window.prompt('Tulis alasan banding dan penjelasan tambahan:'); if (!reason?.trim()) return; await updateTrip(t.id, { banding_reason: reason, banding_at: new Date().toISOString(), status: 'Pending HR Settlement Review' }); await supabase.from('trip_tracking').insert({ trip_id: t.id, actor_name: profile?.name ?? '', actor_role: 'Employee', action: 'Settlement appeal submitted', from_status: t.status, to_status: 'Pending HR Settlement Review', remarks: reason }); showToast('success', 'Banding settlement berhasil diajukan'); refresh(); };

  return <div className="space-y-6 animate-slide-up max-w-5xl mx-auto"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-purple-50 flex items-center justify-center text-purple-600"><FileText className="w-5 h-5" /></div><div><h2 className="text-xl font-bold">Settlement Report</h2><p className="text-sm text-slate-500">Laporan pertanggungjawaban perjalanan dinas</p></div></div>
  {refundQueue.length > 0 && <Card className="p-6 ring-1 ring-rose-200"><div className="flex gap-2"><Banknote className="w-4 h-4 text-rose-600" /><h3 className="text-sm font-bold text-rose-700">Pengembalian Dana Perjalanan Dinas</h3></div><p className="text-xs text-slate-500 my-3">Maksimal file 1 MB. Foto otomatis diperkecil proporsional hingga maksimal 600×600 px.</p>{refundQueue.map((t) => { const url = refundProofs[t.id]; const uploading = refundUploadingTrip === t.id; const submitting = refundSubmittingTrip === t.id; return <div key={t.id} className="rounded-xl ring-1 ring-rose-100 p-4 space-y-3"><div className="flex justify-between"><strong className="text-sm">{t.purpose}</strong><StatusBadge status={t.status} /></div><div className="grid md:grid-cols-3 gap-3"><SummaryBox label="Advance Accountable" value={Number(t.cost_data?.accountable?.total) || 0} /><SummaryBox label="Actual Approved" value={Number(t.approved_total) || 0} /><SummaryBox label="Refund" value={getRefundAmount(t)} /></div><input type="file" accept="image/*,.pdf" disabled={uploading || submitting} onChange={(e) => uploadRefundProof(t, e.target.files?.[0] ?? null)} />{url && <div className="text-xs text-emerald-600 flex gap-1"><CheckCircle2 className="w-3.5 h-3.5" />Bukti terunggah</div>}<Button size="sm" disabled={!url || uploading || submitting} onClick={() => submitRefundProof(t)}>Kirim ke HR</Button></div>; })}</Card>}
  {bandingQueue.length > 0 && <Card className="p-6"><h3 className="text-sm font-bold flex gap-2"><RotateCcw className="w-4 h-4" />Banding Settlement</h3>{bandingQueue.map((t) => <div key={t.id} className="flex justify-between p-3"><span>{t.purpose}</span><Button size="sm" variant="secondary" onClick={() => ajukanBanding(t)}>Ajukan Banding</Button></div>)}</Card>}
  {!selected && <Card className="p-6">{queue.length === 0 ? <EmptyState icon={<MapPin className="w-6 h-6" />} title="Tidak ada trip untuk settlement" /> : queue.map((t) => <div key={t.id} className="p-4 flex justify-between ring-1 ring-slate-100 rounded-xl mb-2"><div><strong className="text-sm">{t.purpose}</strong><div className="text-xs text-slate-400">{formatDate(t.departure_date)} · {formatIDR(Number(t.cost_grand_total) || 0)}</div></div><Button size="sm" onClick={() => startReport(t)}>Isi Laporan</Button></div>)}</Card>}
  {selected && <><Card className="p-6 space-y-4"><div className="flex justify-between"><h3 className="text-sm font-bold">Form Laporan Pertanggungjawaban</h3><button onClick={() => setSelected(null)}>Tutup</button></div><Field label="Laporan Hasil Pekerjaan" required><Textarea rows={4} value={workResult} onChange={(e) => setWorkResult(e.target.value)} /></Field><div className="grid md:grid-cols-3 gap-4"><Field label="Tanggal Realisasi Selesai"><Input type="date" value={selected.return_date} disabled /></Field><Field label="Total Hari Riil"><Input type="number" min={1} value={realDays} onChange={(e) => setRealDays(parseInt(e.target.value) || 1)} /></Field><Field label="Advance Diterima"><Input value={formatIDR(Number(selected.cost_grand_total) || 0)} disabled /></Field></div><div className="grid md:grid-cols-2 gap-4"><Field label="Pending Task"><Textarea rows={2} value={pendingTask} onChange={(e) => setPendingTask(e.target.value)} /></Field><Field label="Next Project"><Textarea rows={2} value={nextProject} onChange={(e) => setNextProject(e.target.value)} /></Field></div></Card>
  <Card className="p-6 space-y-4"><div className="flex justify-between"><h3 className="text-sm font-bold flex gap-2"><Camera className="w-4 h-4" />Rincian Pengeluaran Aktual + Bukti</h3><Button size="sm" variant="secondary" icon={<Plus className="w-3.5 h-3.5" />} onClick={addReceipt}>Add Row</Button></div><p className="text-[11px] text-amber-600 flex gap-1"><AlertCircle className="w-3 h-3" /> Maksimal file 1 MB. Foto otomatis maksimal 600×600 px dengan rasio tetap.</p>{receipts.length === 0 ? <EmptyState icon={<Upload className="w-6 h-6" />} title="Belum ada receipt" /> : receipts.map((r, i) => <div key={r.id} className="rounded-xl ring-1 ring-slate-200 p-3 space-y-2"><div className="flex justify-between"><strong className="text-xs">Receipt {i + 1}</strong><button onClick={() => removeReceipt(r.id)}><Trash2 className="w-4 h-4 text-rose-500" /></button></div><div className="grid md:grid-cols-4 gap-2"><Select value={r.category} onChange={(e) => updateReceipt(r.id, { category: e.target.value })}>{RECEIPT_CATEGORIES.map((c) => <option key={c}>{c}</option>)}</Select><Input value={r.description} onChange={(e) => updateReceipt(r.id, { description: e.target.value })} placeholder="Deskripsi" /><Input type="number" min={0} value={r.amount} onChange={(e) => updateReceipt(r.id, { amount: parseFloat(e.target.value) || 0 })} /><div className="text-xs p-2 bg-slate-50 rounded-xl">{r.uploading ? 'Uploading...' : r.fileUrl ? 'Bukti terunggah' : 'Belum ada bukti'}</div></div><input type="file" accept="image/*,.pdf" onChange={(e) => uploadReceiptImage(r.id, e.target.files?.[0] ?? null)} /></div>)}<div className="flex justify-between border-t pt-3"><strong>Total Pengeluaran Aktual</strong><strong>{formatIDR(totalActual)}</strong></div></Card>
  {validation.length > 0 && <div className="rounded-xl bg-amber-50 p-4 text-xs text-amber-700">{validation.map((e, i) => <div key={i}>• {e}</div>)}</div>}<div className="flex justify-end gap-2 pb-6"><Button variant="secondary" onClick={() => setSelected(null)}>Cancel</Button><Button onClick={submit} disabled={!canSubmit} icon={<Send className="w-4 h-4" />}>Submit Settlement</Button></div></>}</div>;
}
function SummaryBox({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-slate-50 border p-3"><div className="text-[10px] uppercase text-slate-400">{label}</div><div className="text-base font-bold mt-1">{formatIDR(value)}</div></div>; }
